name: Selective copy

on:
  pull_request:
    branches: [main]
    types: [closed]

permissions:
  pull-requests: read

jobs:
  selectivecopy:
    if: github.event.pull_request.merged == true
    name: Selective Copy to temp folder
    runs-on: ubuntu-latest
    steps:

    - uses: actions/checkout@v2
      with:
        fetch-depth: 0

    - name: Run bash and python script
      if: github.event.pull_request.merged == true
      run: |
        chmod -R 777 .
        echo "GITHUB_WORKSPACE: $GITHUB_WORKSPACE"
        echo "github ref: $GITHUB_REF"
        echo "github ref name: $GITHUB_REF_NAME"
        echo "github sha: $GITHUB_SHA"
        echo "pr number: ${{ steps.pr.outputs.pull_request_number }}"
        PR_NUMBER=$(echo $GITHUB_REF | awk 'BEGIN { FS = "/" } ; { print $3 }')
        echo "pr number: $PR_NUMBER"
        echo "pr number: ${{ github.event.number }}"
        python --version
        ./copy_changed_files_to_temp_folder.sh $GITHUB_REF_NAME $GITHUB_WORKSPACE/tmp/ snowflake ${{ steps.pr.outputs.pull_request_number }}
        
