name: Selective copy

on:
  pull_request:
    branches: [main]
    types: [closed]
      

jobs:
  selectivecopy:
    name: Selective Copy to temp folder
    runs-on: ubuntu-latest
    steps:

    - uses: actions/checkout@v2
      with:
        fetch-depth: 0

    - name: Run python script
      run: |
        chmod -R 777 .
        echo "GITHUB_WORKSPACE: $GITHUB_WORKSPACE"
        echo "github ref: $GITHUB_REF"
        echo "github ref name: $GITHUB_REF_NAME"
        echo "github sha: $GITHUB_SHA"
        python --version
        ./copy_changed_files_to_temp_folder.sh $GITHUB_REF_NAME $GITHUB_WORKSPACE/tmp/ snowflake
        
